networks:
  web:
    driver: bridge
    name: traefik-web
  dmz:
    external: true
      

services:
  traefik:
    image: traefik:v3.6
    restart: unless-stopped
    container_name: traefik
    command:
      - "--configFile=/etc/traefik/traefik.toml"
    labels:
      # Enable selfâ€‘routing
      - "traefik.enable=true"

    ports:
      - "${HOST_BINDING_IP:?$HOST_BINDING_IP required}:80:80"
      # - "${HOST_BINDING_IP:?$HOST_BINDING_IP required}:443:443"
      - "${HOST_BINDING_IP:?$HOST_BINDING_IP required}:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - ./logs:/var/log/traefik
    networks:
      - web
      - dmz
